ExilenceNextApp/src/components/item-table/ItemTable.tsx
ExilenceNextApp/src/components/item-table/item-table-header/ItemTableHeader.tsx
ExilenceNextApp/src/components/item-table/item-table-row/ItemTableRow.tsx
ExilenceNextApp/src/interfaces/column.interface.ts
ExilenceNextApp/src/interfaces/priced-item.interface.ts
ExilenceNextApp/src/interfaces/table-item.interface.ts
ExilenceNextApp/src/utils/price.utils.ts

Implemented basic sorting to item table. 
I had to rework the entire component a bit for this to work, and I think we should make this more generic later (to support other tables such as areas, ladder etc).
Fixes #27

Reworks to item table

---

ExilenceNextApp/src/routes/net-worth/NetWorth.tsx

Fix to price retrieval

---

ExilenceNextApp/src/store/domains/profile.ts
ExilenceNextApp/src/store/notificationStore.ts

Added simple length limitation to notifications and local snapshots.
Fixes #43 
Fixes #44

Now limits notification count and local snapshots count

---

ExilenceNextApp/package-lock.json
ExilenceNextApp/package.json
ExilenceNextApp/public/electron.js
ExilenceNextApp/src/components/header/Header.tsx

Initial version of auto updater. Created a task for enhancing this further with more options for the user.
Fixes #16

First working version of auto updater

---

ExilenceNextApp/public/i18n/en/tables.json
ExilenceNextApp/src/components/item-table/ItemTable.tsx
ExilenceNextApp/src/components/item-table/ItemTableContainer.tsx
ExilenceNextApp/src/components/item-table/item-table-filter/ItemTableFilter.tsx

Added item filter to ItemTable

---

ExilenceNextApp/src/components/item-table/ItemTableContainer.tsx
ExilenceNextApp/src/components/toolbar/Toolbar.tsx
ExilenceNextApp/src/components/toolbar/ToolbarContainer.tsx
ExilenceNextApp/src/store/domains/profile.ts

Added button for clearing snapshots

---

ExilenceNextApp/public/i18n/en/common.json
ExilenceNextApp/src/components/toolbar/Toolbar.tsx

Added title for icons and loading icon while fetching snapshots

---

ExilenceNextApp/src/components/item-table/ItemTableContainer.tsx
ExilenceNextApp/src/store/domains/profile.ts
ExilenceNextApp/src/store/uiStateStore.ts

Filter fixes

---

ExilenceNextApp/src/components/toolbar/Toolbar.tsx

Categorize iconareas in toolbar

---

ExilenceNextApp/package-lock.json
ExilenceNextApp/package.json

Updated create-react-app

---

ExilenceNextApp/package-lock.json
ExilenceNextApp/package.json
ExilenceNextApp/src/components/toolbar/Toolbar.tsx

Disabled profile actions while snapshotting

---

ExilenceNextApp/.eslintrc.json
ExilenceNextApp/public/i18n/en/common.json
ExilenceNextApp/src/components/confirmation-dialog/ConfirmationDialog.tsx
ExilenceNextApp/src/components/toolbar/ToolbarContainer.tsx

Created generic modal for confirmation

---

ExilenceNextApp/package-lock.json
ExilenceNextApp/package.json
ExilenceNextApp/public/i18n/en/common.json
ExilenceNextApp/src/components/item-table/ItemTableContainer.tsx
ExilenceNextApp/src/utils/export.utils.ts

Created basic csv export for net worth

---

ExilenceNextApp/package-lock.json
ExilenceNextApp/src/assets/themes/exilence-theme.tsx
ExilenceNextApp/src/components/header/Header.tsx

Increased hitbox for window handler icons and change backgroundcolor on hover.
Fixes #131
Fixes #133

Windowhandlers changed

---

ExilenceNextApp/src/interfaces/profile.interface.ts
ExilenceNextApp/src/store/accountStore.ts
ExilenceNextApp/src/store/domains/account.ts
ExilenceNextApp/src/store/domains/profile.ts

Now sets default stash tabs for first profile

---

ExilenceNextApp/public/i18n/en/common.json
ExilenceNextApp/public/i18n/en/notification.json
ExilenceNextApp/src/components/toolbar/Toolbar.tsx
ExilenceNextApp/src/components/toolbar/ToolbarContainer.tsx
ExilenceNextApp/src/store/domains/account.ts

Added the ability to remove profiles

---

ExilenceNextApp/package-lock.json
ExilenceNextApp/package.json
ExilenceNextApp/public/electron.js

Now maintains window state between launches

---

ExilenceNextApp/src/components/login-content/account-validation-form/AccountValidationForm.tsx
ExilenceNextApp/src/components/sidenav/SideNav.tsx
ExilenceNextApp/src/services/electron.service.ts
ExilenceNextApp/src/utils/window.utils.ts

Changed how external links are handled

---

ExilenceNextApp/public/i18n/en/notification.json
ExilenceNextApp/src/store/accountStore.ts

Created a first version of this. Basically it only retries after 30 seconds if the previous call fails, nothing more. Should be good enough for our first release.
Fixes #175

Retries initSession after 30 seconds if it fails

---

ExilenceNextApp/public/i18n/en/common.json
ExilenceNextApp/src/assets/themes/exilence-theme.tsx
ExilenceNextApp/src/components/item-table/ItemTableContainer.tsx
ExilenceNextApp/src/components/item-table/item-table-cell/ItemTableCell.tsx

Fixes #176
Fixes #184
Fixes #170

minor style enhancements

---

ExilenceNextApp/package-lock.json
ExilenceNextApp/public/i18n/en/common.json
ExilenceNextApp/src/components/item-table/ItemTableContainer.tsx
ExilenceNextApp/src/components/toolbar/Toolbar.tsx
ExilenceNextApp/src/components/toolbar/ToolbarContainer.tsx
ExilenceNextApp/src/store/accountStore.ts
ExilenceNextApp/src/store/uiStateStore.ts

Added loadingspinner on init

---

ExilenceNextApp/src/components/item-table/ItemTable.tsx
ExilenceNextApp/src/components/notification-list/notification-list-item/NotificationListItem.tsx
ExilenceNextApp/src/components/toolbar/Toolbar.tsx

minor UI enhancements

---

ExilenceNextApp/package-lock.json
ExilenceNextApp/src/components/item-table/ItemTable.tsx
ExilenceNextApp/src/components/item-table/ItemTableContainer.tsx

Setting pagination to first page when filter/sorting

---

ExilenceNextApp/src/components/notification-list/notification-list-item/NotificationListItem.tsx

Added description to notifications, with minor styling adjustments

---

ExilenceNextApp/public/i18n/en/common.json
ExilenceNextApp/src/components/password-field/PasswordField.tsx
ExilenceNextApp/src/components/select-field/SelectField.tsx
ExilenceNextApp/src/components/simple-field/SimpleField.tsx
ExilenceNextApp/src/components/visibility-icon/VisibilityIcon.tsx
ExilenceNextApp/src/hooks/use-label-width.ts

Created a base set of components for Formik 2, with a custom hook for handling label width for outlined fields.
Fixes #247

Created a base set of components for Formik 2

---

ExilenceNextApp/package-lock.json
ExilenceNextApp/src/components/notification-list/notification-list-item/NotificationListItem.tsx

Fix for notification time bug

---

ExilenceNextApp/src/store/domains/account.ts
ExilenceNextApp/src/store/signalrStore.ts

Use generic retry strategy for all backend requests

---

ExilenceNextApp/src/interfaces/league.interface.ts
ExilenceNextApp/src/store/accountStore.ts
ExilenceNextApp/src/store/leagueStore.ts
ExilenceNextApp/src/utils/league.utils.ts

Added support for private leagues

---

ExilenceNextApp/package-lock.json
ExilenceNextApp/package.json

Upgraded to Electron 7

---

ExilenceNextBackend/API/Helpers/MiscHelper.cs
ExilenceNextBackend/API/Hubs/AccountHub.cs
ExilenceNextBackend/API/Hubs/BaseHub.cs
ExilenceNextBackend/API/Hubs/GroupHub.cs
ExilenceNextBackend/API/Hubs/SnapshotHub.cs
ExilenceNextBackend/API/Interfaces/ISnapshotService.cs
ExilenceNextBackend/API/Services/SnapshotService.cs
ExilenceNextBackend/Shared/Interfaces/ISnapshotRepository.cs
ExilenceNextBackend/Shared/Repositories/SnapshotRepository.cs
ExilenceNextBackend/Shared/Shared.csproj

Removed all bulkcopy code to use EF instead and added timings to logging

Backend improvements

---

ExilenceNextApp/src/components/item-table/item-table-filter/ItemTableFilter.tsx

Fixes https://github.com/viktorgullmark/exilence-next/issues/509

Prevent search form from being submitted

---

ExilenceNextApp/public/main/overlays/netWorthOverlay.js
ExilenceNextApp/public/main/tray.js

Fixes https://github.com/viktorgullmark/exilence-next/issues/586

hotfix: remove unnecessary window destroy and import

---

CHANGELOG.md
ExilenceNextApp/src/store/accountStore.ts
ExilenceNextApp/src/store/domains/account.ts

Fixed conflicting snapshot/price fetching intervals

---

ExilenceNextBackend/API/Startup.cs
ExilenceNextBackend/Shared/MongoMigrationHandler.cs
ExilenceNextBackend/Shared/MongoMigrations/20201027174100_InitialMigration.cs
ExilenceNextBackend/Shared/Shared.csproj

Added working migration example

---

ExilenceNextApp/src/config/app.config.dev.ts
ExilenceNextBackend/API/Services/SnapshotService.cs
ExilenceNextBackend/Shared/Interfaces/IMongoRepository.cs
ExilenceNextBackend/Shared/Repositories/SnapshotRepository.cs

Also implemented functionality to in the future clear stashtabs along with snapshots when they are saved.

Limit to only save the last 100 snapshots

---

CHANGELOG.md
ExilenceNextApp/src/store/signalrStore.ts
ExilenceNextApp/src/store/uiStateStore.ts

Fixes https://github.com/viktorgullmark/exilence-next/issues/465

Fixed a bug where you couldnt properly switch accounts

---

ExilenceNextApp/src/components/stash-tab-dropdown/StashTabDropdown.tsx

[![Image from Gyazo](https://i.gyazo.com/001e291dcc40475ab70a6db428652e5d.gif)](https://gyazo.com/001e291dcc40475ab70a6db428652e5d)

feat(profile): persist stash selection during profile creation

---

ExilenceNextApp/src/store/accountStore.ts
ExilenceNextApp/src/store/signalrStore.ts

- Removed retry policy when at login screen
- Added working persistence of OAuth token
- Remove authorization header on signout

fix(oauth): misc oauth fixes

---

ExilenceNextApp/public/electron.js

fix(app): protocol on dev env

---

ExilenceNextApp/src/services/pricing.service.ts

Related:
https://github.com/viktorgullmark/exilence-next/issues/699
https://github.com/viktorgullmark/exilence-next/issues/698

fix(net-worth): show divination cards again

---

ExilenceNextApp/src/store/domains/account-league.ts
ExilenceNextApp/src/store/domains/profile.ts

Few more fixes for our console users. This one is the final final (again)(gone wrong).

fix(account): omitted platform params in few other functions

---

ExilenceNextApp/src/services/poe-ninja.service.ts

Just added some catagories, tested with linux build.
Again, thanks for your support linux community.
https://github.com/viktorgullmark/exilence-next/issues/709

 now total 26 categories

---

ExilenceNextApp/src/components/drawer-wrapper/navigation-menu/NavigationMenu.tsx

https://gyazo.com/344bc42a49290144432e560919fcf604

feat(menu): added tooltips to menu icons

---

ExilenceNextApp/public/i18n/en/common.json
ExilenceNextApp/src/components/toolbar/Toolbar.tsx
ExilenceNextApp/src/components/toolbar/ToolbarContainer.tsx
ExilenceNextApp/src/store/settingStore.ts

feat(misc): autosnapshotting tweaks

---

ExilenceNextApp/src/components/sparkline-chart/SparklineChart.tsx

Fixes Victory gradient related errors

fix: victory chart gradient errors

---

ExilenceNextApp/public/electron.js
ExilenceNextApp/public/i18n/en/common.json
ExilenceNextApp/public/main/localSettings.js
ExilenceNextApp/public/main/tray.js
ExilenceNextApp/src/components/settings-tabs/SettingsTabs.tsx
ExilenceNextApp/src/components/settings-tabs/components/select-setting/SelectSetting.styles.ts
ExilenceNextApp/src/components/settings-tabs/components/select-setting/SelectSetting.tsx
ExilenceNextApp/src/components/settings-tabs/general/app-exit-actions-settings/AppExitActionsSettings.tsx
ExilenceNextApp/src/store/settingStore.ts

feat: add on close actions and fix tray destroy on close

---

ExilenceNextApp/public/i18n/en/stepper.json
ExilenceNextApp/src/components/overview-widget-content/OverviewWidgetContent.tsx
ExilenceNextApp/src/utils/stepper.utils.ts

Added steps to describe new functions

---

ExilenceNextApp/src/components/sparkline-chart/SparklineChart.tsx

fix: interpolation clipping

---

CHANGELOG.md
ExilenceNextApp/src/components/columns/Columns.styles.ts
ExilenceNextApp/src/components/columns/Columns.tsx
ExilenceNextApp/src/components/item-table/itemTableBulkSellColumns.ts
ExilenceNextApp/src/components/item-table/itemTableColumns.ts
ExilenceNextApp/src/components/price-table/priceTableColumns.ts
ExilenceNextApp/src/components/table-wrapper/TableWrapper.styles.ts
ExilenceNextApp/src/components/table-wrapper/TableWrapper.tsx
ExilenceNextApp/src/interfaces/external-price.interface.ts
ExilenceNextApp/src/utils/price.utils.ts

feat(table): price history column with sparkline

---

CHANGELOG.md
ExilenceNextApp/public/i18n/en/common.json
ExilenceNextApp/src/components/columns/Columns.styles.ts
ExilenceNextApp/src/components/columns/Columns.tsx
ExilenceNextApp/src/components/item-table/ItemTableContainer.tsx
ExilenceNextApp/src/components/item-table/item-table-filter/ItemTableFilter.styles.ts
ExilenceNextApp/src/components/item-table/item-table-filter/ItemTableFilter.tsx
ExilenceNextApp/src/components/item-table/itemTableBulkSellColumns.ts
ExilenceNextApp/src/components/item-table/itemTableColumns.ts
ExilenceNextApp/src/components/item-table/itemTableComparisonColumns.ts
ExilenceNextApp/src/components/item-table/itemTableGroupColumns.ts
ExilenceNextApp/src/interfaces/api/api-priced-item.interface.ts
ExilenceNextApp/src/interfaces/api/api-priced-items-update.interface.ts
ExilenceNextApp/src/interfaces/api/api-stashtab-priceditem.interface.ts
ExilenceNextApp/src/store/domains/group.ts
ExilenceNextApp/src/store/domains/profile.ts
ExilenceNextApp/src/store/uiStateStore.ts
ExilenceNextApp/src/types/item-table-selection.type.ts
ExilenceNextApp/src/utils/snapshot.utils.ts

feat(diff): added functionality for comparing latest two snapshots

---

CHANGELOG.md
ExilenceNextApp/package-lock.json
ExilenceNextApp/package.json
ExilenceNextApp/public/i18n/en/common.json
ExilenceNextApp/src/components/settings-tabs/advanced/reset-indexeddb-settings/ResetIndexedDbSettings.tsx
ExilenceNextApp/src/components/toolbar/Toolbar.tsx
ExilenceNextApp/src/config/axios.ts
ExilenceNextApp/src/index.tsx
ExilenceNextApp/src/services/external.service.ts
ExilenceNextApp/src/store/domains/account-league.ts
ExilenceNextApp/src/store/domains/profile.ts
ExilenceNextApp/src/store/rateLimitStore.ts

feat(limiter): reworked how we handle ratelimits for pathofexile.com

---

CHANGELOG.md
ExilenceNextApp/src/store/domains/group.ts
ExilenceNextApp/src/store/domains/profile.ts

fix(income): income calculations werent converted correctly to exalts
